[build]
  publish = "public"
  functions = "netlify/functions"

# Se o front usa /api/app/*
[[redirects]]
  from = "/api/app/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

# (Opcional) também aceite /api/index/* se quiser
[[redirects]]
  from = "/api/index/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
